@startuml
title Smart Home Monolith Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of the Smart Home system")

Container_Boundary(SmartHomeSystem, "Smart Home System") {
    System(HeatingSubDomain, "Managing heating system", "Managing heating system")
    System(TemperatureSubDomain, "Monitoring temperature", "Monitoring temperature")
}

System_Ext(sensors, "Temperature Sensors", "Temperature Sensors", "REST API")
System_Ext(heatingSystem, "Heating System", "Heating System", "REST API")

Rel(user, SmartHomeSystem, "Uses the system")
Rel(TemperatureSubDomain,sensors,"Fetches the current temperature")
Rel(HeatingSubDomain,heatingSystem,"Set configuration")

@enduml